function F = fimathLike(X, roundingMethod, overflowAction)
    %fimathLike fimath like input.
    %   F = fixed.fimathLike(X) returns fimath object F with its sum and
    %   product modes set to the same numeric properties as X where X is a
    %   fi object or numerictype object, with RoundingMethod set to Floor
    %   and OverflowAction set to Wrap.
    %
    %   F = fixed.fimathLike(X, roundingMethod, overflowAction) is as
    %   before, but with RoundingMethod set to roundingMethod and
    %   OverflowAction set to overflowAction.
    %
    %   If X is not a fi object or numerictype object, then empty
    %   is returned.
    %
    %   Example:
    %     X = fi(1,1,8,0);
    %     F = fixed.fimathLike(X)
    %     X(:) = setfimath(X,F) + 1

    %   Copyright 2020-2022 The MathWorks, Inc.
    %#codegen
    if nargin < 2
        roundingMethod = 'Floor';
    end
    if nargin < 3
        overflowAction = 'Wrap';
    end
    fixed.internal.validation.validateNumericOrNumericType(mfilename,X);
    if ((isfi(X) || isnumerictype(X) || isa(X,'Simulink.NumericType')) ...
            && isscaledtype(X)) 
        if isscalingbinarypoint(X)
            % Binary point scaling
            w = X.WordLength;
            f = X.FractionLength;
            F = fimath(...
                'RoundingMethod', roundingMethod, ...
                'OverflowAction', overflowAction, ...
                'ProductMode', 'SpecifyPrecision', ...
                'ProductWordLength', w, ...
                'ProductFractionLength', f, ...
                'SumMode', 'SpecifyPrecision', ...
                'SumWordLength', w, ...
                'SumFractionLength', f, ...
                'CastBeforeSum', true);
        else
            % Slope bias scaling
            w = X.WordLength;
            fe = X.FixedExponent;
            saf = X.SlopeAdjustmentFactor;
            bias = X.Bias;
            F = fimath(...
                'RoundingMethod', roundingMethod, ...
                'OverflowAction', overflowAction, ...
                'ProductMode', 'SpecifyPrecision', ...
                'ProductWordLength', w, ...
                'ProductFixedExponent', fe, ...
                'ProductSlopeAdjustmentFactor',saf,...
                'ProductBias',bias,...
                'SumMode', 'SpecifyPrecision', ...
                'SumWordLength', w, ...
                'SumFixedExponent', fe, ...
                'SumSlopeAdjustmentFactor',saf,...
                'SumBias', bias,...
                'CastBeforeSum', true);
        end
    else
        % Not fi or numerictype
        F = cast([],'like',X);
    end
end

