function clean_examples
    %clean_examples Remove files generated by examples
    delete *.mex*
    delete *.asv
    delete *.slxc
    delete_dirs = ["codegen"
        "instrumentation"
        "fiaccel"
        "slprj"
        "hdlsrc"
        "html"];
    for k = 1:length(delete_dirs)
        status = rmdir(delete_dirs(k),"s"); %#ok<NASGU> 
    end
    current_dir = pwd;
    d = dir;
    for n=1:length(d)
        if d(n).isdir ...
                && ~isequal(d(n).name,'.') ...
                && ~isequal(d(n).name,'..')
            cd(d(n).name);
            clean_examples;
            cd(current_dir)
        end
    end
end
