function hdlsetupFixedMatrixLibrary(model)
%hdlsetupFixedMatrixLibrary Set Simulink model parameters for HDL code generation.
%   fixed.example.hdlsetupFixedMatrixLibrary('model') changes the parameters of the Simulink model
%   specified by the 'model' argument to values that are commonly used for
%   HDL code generation. The specified model should be open in Simulink
%   before you invoke the hdlsetup command. The hdlsetup command uses the
%   Simulink set_param function to set up models for HDL code generation
%   quickly and consistently. The model parameters settings provided by
%   hdlsetup are intended as useful defaults, but they may not be
%   appropriate for all your applications.
%
%   See also CHECKHDL, HDLSETUP, MAKEHDL, MAKEHDLTB, VISIONHDLSETUP.

%   Copyright 2021-2022 The MathWorks, Inc.
    model = convertStringsToChars(model);

    % Model Parameters
    set_param(model, ...
        'SingleTaskRateTransMsg',    'error', ...
        'MultiTaskRateTransMsg',     'error', ...
        'Solver',                    'fixedstepdiscrete', ...
        'SolverMode',                'SingleTasking', ...
        'FixedStep',                 'auto', ...
        'SaveTime',                  'off', ...
        'SaveOutput',                'off', ...
        'AlgebraicLoopMsg',          'error', ...
        'SampleTimeColors',          'off',...
        'ShowLineDimensions',        'on',...
        'ShowPortDataTypes',         'on',...
        'BlockReduction',            'off',...
        'ConditionallyExecuteInputs','off',...
        'InlineParams',              'on',...
        'ProdHWDeviceType',          'ASIC/FPGA->ASIC/FPGA',...
        'DataTypeOverride',          'ForceOff',...
        'SignalLoggingSaveFormat',   'Dataset',...
        'UnderSpecifiedDimensionMsg','none',...
        'IntegerOverflowMsg','warning',...
        'IntegerSaturationMsg','warning',...
        'FixptConstOverflowMsg','warning',...
        'ParameterDowncastMsg','none',...
        'ParameterUnderflowMsg','none',...
        'ParameterOverflowMsg','none',...
        'ParameterTunabilityLossMsg','none',...
        'ParameterPrecisionLossMsg','none');
    % 'UnderSpecifiedDimensionMsg','none' To prevent HDL Workflow Advisor from
    % error because of the way it handles vectors that get expanded to scalars
    % in "Verify with HDL Cosimulation"

    % Attach HDL Coder specific settings and implementation bindings to this
    % model
    attachhdlcconfig(model);
    try
        hdlset_param(model,'AdaptivePipelining', 'off');
        hdlset_param(model,'BalanceDelays', 'off');
        hdlset_param(model,'ClockRatePipelining', 'off');
        hdlset_param(model,'ShareAtomicSubsystems', 'off');
        hdlset_param(model,'ShareFloatingPointIPs', 'off');
        hdlset_param(model,'ShareMATLABBlocks', 'off');
        hdlset_param(model,'ShareMultipliers', 'off');
        hdlset_param(model,'ShareMultiplyAdds', 'off');
        hdlset_param(model,'TransformNonZeroInitValDelay', 'off');
        hdlset_param(model,'InitializeBlockRAM', 'off');
    catch
        warning(message('fixed:hdlcoder:unsethdlparams'));
    end
end